<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * CarrierServicesSeeder - Seeds all possible carrier service types
 * 
 * This ensures that live API rates always have a matching carrier_service_id,
 * preventing the SELECTED.DESTINATION.SERVICETYPE.INVALID error.
 */
class CarrierServicesSeeder extends Seeder
{
    public function run(): void
    {
        // FedEx Services - All service types that FedEx API can return
        $fedexServices = [
            // International Services
            [
                'carrier_code' => 'fedex',
                'service_code' => 'FEDEX_INTERNATIONAL_PRIORITY',
                'display_name' => 'FedEx International Priority',
                'description' => '1-3 business days to most destinations',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 1,
                'max_transit_days' => 3,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'is_default' => true,
                'sort_order' => 1,
            ],
            [
                'carrier_code' => 'fedex',
                'service_code' => 'FEDEX_INTERNATIONAL_ECONOMY',
                'display_name' => 'FedEx International Economy',
                'description' => '4-6 business days to most destinations',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 4,
                'max_transit_days' => 6,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 2,
            ],
            [
                'carrier_code' => 'fedex',
                'service_code' => 'INTERNATIONAL_FIRST',
                'display_name' => 'FedEx International First',
                'description' => 'Next business day delivery by 8:00 AM',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 1,
                'max_transit_days' => 1,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 3,
            ],
            [
                'carrier_code' => 'fedex',
                'service_code' => 'FEDEX_INTERNATIONAL_PRIORITY_EXPRESS',
                'display_name' => 'FedEx International Priority Express',
                'description' => 'Fastest international delivery',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 1,
                'max_transit_days' => 2,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 4,
            ],
            [
                'carrier_code' => 'fedex',
                'service_code' => 'FEDEX_INTERNATIONAL_GROUND',
                'display_name' => 'FedEx International Ground',
                'description' => 'Ground delivery to Canada',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 5,
                'max_transit_days' => 10,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 5,
            ],
            [
                'carrier_code' => 'fedex',
                'service_code' => 'INTERNATIONAL_ECONOMY_FREIGHT',
                'display_name' => 'FedEx International Economy Freight',
                'description' => 'International freight shipping',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 5,
                'max_transit_days' => 10,
                'sort_order' => 20,
            ],
            [
                'carrier_code' => 'fedex',
                'service_code' => 'INTERNATIONAL_PRIORITY_FREIGHT',
                'display_name' => 'FedEx International Priority Freight',
                'description' => 'International priority freight',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 2,
                'max_transit_days' => 5,
                'sort_order' => 21,
            ],
            // Domestic Services
            [
                'carrier_code' => 'fedex',
                'service_code' => 'FEDEX_GROUND',
                'display_name' => 'FedEx Ground',
                'description' => '1-5 business days',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 1,
                'max_transit_days' => 5,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'is_default' => true,
                'sort_order' => 10,
            ],
            [
                'carrier_code' => 'fedex',
                'service_code' => 'FEDEX_HOME_DELIVERY',
                'display_name' => 'FedEx Home Delivery',
                'description' => 'Residential ground delivery',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 1,
                'max_transit_days' => 5,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 11,
            ],
            [
                'carrier_code' => 'fedex',
                'service_code' => 'GROUND_HOME_DELIVERY',
                'display_name' => 'FedEx Ground Home Delivery',
                'description' => 'Residential ground delivery',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 1,
                'max_transit_days' => 5,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 12,
            ],
            [
                'carrier_code' => 'fedex',
                'service_code' => 'FEDEX_EXPRESS_SAVER',
                'display_name' => 'FedEx Express Saver',
                'description' => '3 business days by 4:30 PM',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 3,
                'max_transit_days' => 3,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 13,
            ],
            [
                'carrier_code' => 'fedex',
                'service_code' => 'FEDEX_2_DAY',
                'display_name' => 'FedEx 2Day',
                'description' => '2 business days by 4:30 PM',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 2,
                'max_transit_days' => 2,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 14,
            ],
            [
                'carrier_code' => 'fedex',
                'service_code' => 'FEDEX_2_DAY_AM',
                'display_name' => 'FedEx 2Day AM',
                'description' => '2 business days by 10:30 AM',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 2,
                'max_transit_days' => 2,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 15,
            ],
            [
                'carrier_code' => 'fedex',
                'service_code' => 'STANDARD_OVERNIGHT',
                'display_name' => 'FedEx Standard Overnight',
                'description' => 'Next business day by 3:00 PM',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 1,
                'max_transit_days' => 1,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 16,
            ],
            [
                'carrier_code' => 'fedex',
                'service_code' => 'PRIORITY_OVERNIGHT',
                'display_name' => 'FedEx Priority Overnight',
                'description' => 'Next business day by 10:30 AM',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 1,
                'max_transit_days' => 1,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 17,
            ],
            [
                'carrier_code' => 'fedex',
                'service_code' => 'FIRST_OVERNIGHT',
                'display_name' => 'FedEx First Overnight',
                'description' => 'Next business day by 8:00 AM',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 1,
                'max_transit_days' => 1,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 18,
            ],
        ];

        // DHL Services
        $dhlServices = [
            [
                'carrier_code' => 'dhl',
                'service_code' => 'EXPRESS_WORLDWIDE',
                'display_name' => 'DHL Express Worldwide',
                'description' => 'International express shipping',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 2,
                'max_transit_days' => 5,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'is_default' => true,
                'sort_order' => 1,
            ],
            [
                'carrier_code' => 'dhl',
                'service_code' => 'P',
                'display_name' => 'DHL Express Worldwide',
                'description' => 'International express shipping (API code)',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 2,
                'max_transit_days' => 5,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 2,
            ],
            [
                'carrier_code' => 'dhl',
                'service_code' => 'EXPRESS_9_00',
                'display_name' => 'DHL Express 9:00',
                'description' => 'Delivery by 9:00 AM',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 1,
                'max_transit_days' => 2,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 3,
            ],
            [
                'carrier_code' => 'dhl',
                'service_code' => 'EXPRESS_10_30',
                'display_name' => 'DHL Express 10:30',
                'description' => 'Delivery by 10:30 AM',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 1,
                'max_transit_days' => 2,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 4,
            ],
            [
                'carrier_code' => 'dhl',
                'service_code' => 'EXPRESS_12_00',
                'display_name' => 'DHL Express 12:00',
                'description' => 'Delivery by 12:00 PM',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 1,
                'max_transit_days' => 2,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 5,
            ],
            [
                'carrier_code' => 'dhl',
                'service_code' => 'ECONOMY_SELECT',
                'display_name' => 'DHL Economy Select',
                'description' => 'Cost-effective international shipping',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 5,
                'max_transit_days' => 10,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 6,
            ],
        ];

        // UPS Services
        $upsServices = [
            // International
            [
                'carrier_code' => 'ups',
                'service_code' => 'UPS_WORLDWIDE_EXPRESS',
                'display_name' => 'UPS Worldwide Express',
                'description' => 'Next day delivery worldwide',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 1,
                'max_transit_days' => 3,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'is_default' => true,
                'sort_order' => 1,
            ],
            [
                'carrier_code' => 'ups',
                'service_code' => 'UPS_WORLDWIDE_EXPEDITED',
                'display_name' => 'UPS Worldwide Expedited',
                'description' => '2-5 business days worldwide',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 2,
                'max_transit_days' => 5,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 2,
            ],
            [
                'carrier_code' => 'ups',
                'service_code' => 'UPS_WORLDWIDE_SAVER',
                'display_name' => 'UPS Worldwide Saver',
                'description' => 'End of day delivery worldwide',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 1,
                'max_transit_days' => 3,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 3,
            ],
            [
                'carrier_code' => 'ups',
                'service_code' => 'UPS_STANDARD',
                'display_name' => 'UPS Standard',
                'description' => 'Day-definite delivery to Canada/Mexico',
                'is_international' => true,
                'is_domestic' => false,
                'base_transit_days' => 3,
                'max_transit_days' => 7,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 4,
            ],
            // Domestic
            [
                'carrier_code' => 'ups',
                'service_code' => 'UPS_GROUND',
                'display_name' => 'UPS Ground',
                'description' => '1-5 business days',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 1,
                'max_transit_days' => 5,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'is_default' => true,
                'sort_order' => 10,
            ],
            [
                'carrier_code' => 'ups',
                'service_code' => 'UPS_3_DAY_SELECT',
                'display_name' => 'UPS 3 Day Select',
                'description' => '3 business days',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 3,
                'max_transit_days' => 3,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 11,
            ],
            [
                'carrier_code' => 'ups',
                'service_code' => 'UPS_2ND_DAY_AIR',
                'display_name' => 'UPS 2nd Day Air',
                'description' => '2 business days',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 2,
                'max_transit_days' => 2,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 12,
            ],
            [
                'carrier_code' => 'ups',
                'service_code' => 'UPS_2ND_DAY_AIR_AM',
                'display_name' => 'UPS 2nd Day Air AM',
                'description' => '2 business days by 10:30 AM',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 2,
                'max_transit_days' => 2,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 13,
            ],
            [
                'carrier_code' => 'ups',
                'service_code' => 'UPS_NEXT_DAY_AIR',
                'display_name' => 'UPS Next Day Air',
                'description' => 'Next business day',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 1,
                'max_transit_days' => 1,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 14,
            ],
            [
                'carrier_code' => 'ups',
                'service_code' => 'UPS_NEXT_DAY_AIR_SAVER',
                'display_name' => 'UPS Next Day Air Saver',
                'description' => 'Next business day by end of day',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 1,
                'max_transit_days' => 1,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 15,
            ],
            [
                'carrier_code' => 'ups',
                'service_code' => 'UPS_NEXT_DAY_AIR_EARLY',
                'display_name' => 'UPS Next Day Air Early',
                'description' => 'Next business day by 8:00 AM',
                'is_international' => false,
                'is_domestic' => true,
                'base_transit_days' => 1,
                'max_transit_days' => 1,
                'max_weight_lb' => 150,
                'max_weight_kg' => 68,
                'sort_order' => 16,
            ],
        ];

        $allServices = array_merge($fedexServices, $dhlServices, $upsServices);

        foreach ($allServices as $service) {
            // Check if service already exists
            $existing = DB::table('carrier_services')
                ->where('carrier_code', $service['carrier_code'])
                ->where('service_code', $service['service_code'])
                ->first();

            $data = array_merge([
                'is_active' => true,
                'is_default' => false,
            ], $service);

            if ($existing) {
                // Update existing record
                DB::table('carrier_services')
                    ->where('id', $existing->id)
                    ->update(array_merge($data, ['updated_at' => now()]));
            } else {
                // Insert new record
                DB::table('carrier_services')->insert(array_merge($data, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ]));
            }
        }

        $this->command->info('Seeded ' . count($allServices) . ' carrier services.');
    }
}
