<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Add EEI (Electronic Export Information) code to ships table.
     * EEI code is per shipment, not per item, and may be generated by courier.
     */
    public function up(): void
    {
        Schema::table('ships', function (Blueprint $table) {
            $table->string('eei_code', 50)->nullable()->after('declared_value_currency');
            $table->boolean('eei_required')->default(false)->after('eei_code');
            $table->text('eei_exemption_reason')->nullable()->after('eei_required');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('ships', function (Blueprint $table) {
            $table->dropColumn(['eei_code', 'eei_required', 'eei_exemption_reason']);
        });
    }
};
